### ISSUE TITLE
zipprofile failure

### ISSUE THREAD

**Issue by simplextech** [Einstein42/udi-lifx-poly#2]
Missing dependency on a fresh Raspbian Lite install

zip is not installed by default and the zipprofile script calls zip which fails and causes the install to file from within Polyglot-v2

Updating the install script for polyglot-v2 and instructions would correct the install failure.

**Comment by exking** [comment]
zipprofile is a historical script, it's not used in the primary install path. Polyglot has been changed to upload profiles without zipping them up so zip installation is not required

**Comment by simplextech** [comment]
Excellent that it's no longer needed.  I went in circles for a bit because of the install failing until I dug into the install process and saw that it was calling zip.
